### ISSUE TITLE
Rename LightGraphs to Graphs

### ISSUE THREAD

**Issue by tai** [daschw/SankeyPlots.jl#13]
Due to the "LightGraphs.jl -> Graphs.jl" rename, SankeyPlots stopped working with graphs built on top of new Graphs.jl-based types. For the detail of this rename, please check out following:

LightGraphs.jl Transition
- https://discourse.julialang.org/t/lightgraphs-jl-transition/69526/11

With this rename, old "Graphs.jl" has retired as "OldGraphs.jl" and newer version of "LightGraphs.jl" is now "Graphs.jl". This caused modules using LightGraphs to fail with Graphs-based types, as method dispatch now fails.

Simply changing "using LightGraphs" to "using Graphs" should do the migration.

**Comment by davide-f** [comment]
In my fork I solved the recent problems (https://github.com/davide-f/SankeyPlots.jl/).
I added pull requests here as well, yet my fork is working now.
I look forward for merging the pull requests; co-ownership possible?

Temporary fix:

Pkg.add(url="https://github.com/davide-f/SankeyPlots.jl", rev="master")

**Comment by davide-f** [comment]
#15 solves this issue
