### ISSUE TITLE
Broken out of the box

### ISSUE THREAD

**Issue by leephillips** [daschw/SankeyPlots.jl#14]
Freshly installed with Julia 1.7, running the example gets me:

```
julia> sankey(src, dst, weights)
ERROR: MethodError: no method matching vertices(::SimpleWeightedGraphs.SimpleWeightedDiGraph{Int64, Float64})
Closest candidates are:
  vertices(::LightGraphs.SimpleGraphs.AbstractSimpleGraph) at /home/lee/.julia/packages/LightGraphs/IgJif/src/SimpleGraphs/SimpleGraphs.jl:58
  vertices(::LightGraphs.AbstractGraph) at /home/lee/.julia/packages/LightGraphs/IgJif/src/interface.jl:181
```

**Comment by davide-f** [comment]
In my fork I solved the recent problems (https://github.com/davide-f/SankeyPlots.jl/).
I added pull requests here as well, yet my fork is working now.
I look forward for merging the pull requests; co-ownership possible?

**Comment by leephillips** [comment]
This is great news. Is your question for me? What is "co-ownership"?

**Comment by davide-f** [comment]
The question may be more for @daschw, in the case he is not able to take care of the repo.
The fix is ready but we cannot fix it, yet you may use my repo instead on this in the meantime

Pkg.add(url="https://github.com/davide-f/SankeyPlots.jl", rev="master")

**Comment by leephillips** [comment]
Fantastic, I’ll use your fork. Thank you for fixing it.

**Comment by daschw** [comment]
Thanks a lot for the contributions @davide-f ! Indeed, I have difficulties to find time to maintain this repo, so I very much welcome co-ownership. As a first step I've added you as a contributor to the repo. Not sure, if you have sufficient rights now to merge PRs. You can try to merge #16, if you want.

**Comment by davide-f** [comment]
@daschw Thank you very much!
It seems I can run tests and the botton "merge" appeared, thought not green as the tests are ongoing.
In case of problems with permissions, I will ask support. Thank you!

**Comment by davide-f** [comment]
Pull request #15 fixes this problem.
@daschw I do have permissions successfully, confirmed. I close this issue
