### ISSUE TITLE
Suggest ordering of the elements

### ISSUE THREAD

**Issue by davide-f** [daschw/SankeyPlots.jl#3]
Another interesting part would be to preserve the ordering of the elements in the vector source/target.
This can be useful to model for example when an user produce something that he uses himself (this applies to my case)

I would add, maybe linked to the above, that it would be nice to specify the layer where a node should be put.
For example, in the following image, I would like to move the blue square in the middle column to the third layer.
(Moreover, I would like to put the boxes of the same colors on the same "row", possibly)
![SampleSankey](https://user-images.githubusercontent.com/67809479/109395998-a8f53c80-792f-11eb-9b9e-69f8ec85eaa5.png)

Thank you

**Comment by daschw** [comment]
This would have to be implemented in the algorithm in LayeredLayouts. @oxinabox, would this be possible to add?

**Comment by oxinabox** [comment]
I think so.
@davide-f can you maybe 2 seperate issues on LayeredLayouts.jl, one for each of these?
They sound like something I also want.
No promises when I will be able to get around to them. But definitely let's track them.
(I am also happy to talk someone through adding them)

**Comment by davide-f** [comment]
Thank you for the answers; I have added the two different issues.

**Comment by davide-f** [comment]
I have added pull requests on LayeredLayouts to address this point and I have ready a pull request for SankeyPlots; I wait for the final implementation in LayeredLayouts to suggest any change here

**Comment by Mastomaki** [comment]
>This can be useful to model for example when an user produce something that he uses himself (this applies to my case)

Or in any case there can be flows node a -> node b and backward flow node b -> node a. Is this possible currently?

**Comment by davide-f** [comment]
@Mastomaki SankeyPlots enables to describe flows between nodes. Typically flows go from left to right, but there is no "directionality" so it should work both ways, but be aware that you cannot draw two flows between the same two nodes.

Regarding this specific issue, let's assume that you are drawing flows between a set of producers A and B to a set of consumers 1,C2& C3.
For description purposes, you may like to have on the left, first producer A and below it producer B, and similarly C1,C2&C3.
Once this issue is solved, you can specify the row ordering in which A,B,C1,C2,C3 are ordered.
In particular it will be possible to specify A before B or also B before A.

**Comment by Mastomaki** [comment]
To clarify that we are talking about the same thing, I mean the recycling stream in [here](https://ec.europa.eu/eurostat/web/circular-economy/material-flow-diagram).

**Comment by davide-f** [comment]
@Mastomaki What you mentioned is pretty interesting; actually, I have no idea if that works, the best way is to test it and see what happens.
That depends on the interaction of the code with LayerLayouts and the specific algorithm used in the latter.

You may create a very simple example on the above and add an issue with the output, if you wish.

Update: I created a very super simple test: LayeredLayouts rely on only Directed Acylic Graphs, thus there cannot be any loops, which would be needed to draw the recycle component. Addressing recycling needs quite heavy changes to the current script and dependencies
