### ISSUE TITLE
Visualization improvement

### ISSUE THREAD

**Issue by davide-f** [daschw/SankeyPlots.jl#4]
Dear Community,
I believe that the visualization may be improved with some settings to specify the minimum distance between the flows, for example.
When the number of elements increase, the quality of the visualization drops significantly as the number of flows increase.
It would be nice to find some way to improve, eventually personalizing the minimum distance of the flows.
![Sankey2](https://user-images.githubusercontent.com/67809479/109397281-49e6f600-7936-11eb-8b8c-87e73ec07f12.png)

**Comment by daschw** [comment]
I implemented the `compact` keyword, illustrated in the second example in the README. Let me know if this does not solve the issue for you.

**Comment by davide-f** [comment]
Thank you for the improvement, I haven't had the time to check yet, but I'll do in the next days and I am sure this has solved my issue.
Thank you
